config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    # pertains to individual members of a post
    member do 
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:create, :show, :new]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: "User"
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = 'Your comment was added.'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote] )
    
    respond_to do |format|
      format.html do 
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You already voted"
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit!
  end
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br>
    <span id="comment_<%= comment.id %>_votes"><%= comment.diff_votes%> votes</span>
    <br>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>

  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
    on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br>
    by <%= link_to comment.creator.username, '' %> at <%= display_datetime(comment.created_at) %>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.diff_votes %> votes")
<% else %>
  alert("You've already voted.")
<% end %>