config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    # pertains to individual members of a post
    member do 
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:create, :show, :new]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: "user_id", class_name: "User"
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_permissions, only: [:edit, :update]
  def index
    @posts = Post.all.sort_by{|x| x.diff_votes}.reverse
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  def new 
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Post was created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit;  end

  def update
    if @post.update(post_params)
      flash[:notice] = "this post was updated."
      redirect_to post_path(@path)
    else
      render "/posts/show"
    end   
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do 
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You already voted"
        end
        redirect_to :back
      end
      format.js
    end    
  end

  private

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def post_params
    params.require(:post).permit!
  end

  def require_permissions
    user = current_user
    post = Post.find_by slug: params[:id]

    access_denied unless logged_in? and (current_user == post.creator || user.admin?)
  end
end

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br>
    <span id="post_<%= post.slug %>_votes"><%= post.diff_votes%> votes</span>
    <br>
    <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by</span> <%= post.creator.username %> 
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/_post_form.html.erb
<%= render "shared/validation_errors", object: post %>

<div class="well">
<%= form_for post do |f| %>
  <div class="control-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="control-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="control-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <div class="control-group">
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") { cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>

  </div>

  <%= f.submit(post.new_record? ? "Create Post": "Update Post", class: 'btn btn-primary') %>

<% end %>
</div>

app/views/posts/edit.html.erb
<%= render "shared/content_title", title: "Edit Post" %>

<%= render "post_form", post: @post %>

app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/content_title", title: "New Post" %>

<%= render "posts/post_form", post: @post %>

<!-- 
<h5>Pure HTML form</h5>
<form action="/posts" method="POST">
  Title: <input type="text" name="my_title">
  <br>
  <input type="submit" class="btn btn-primary">
</form>

<h5>Form Helper</h5>
<%= form_tag '/posts' do %>
  <%= label_tag :title %>
  <%= text_field_tag :title %>
  <br>
  <%= submit_tag "Create Post", class: 'btn btn-primary' %>
<% end %>
 -->

app/views/posts/show.html.erb
<p class="pull-right">
  [<%= link_to 'edit this post', edit_post_path(@post) %>]
</p>

<p>
  <%= render @post.categories %>
</p>

<%= render "shared/content_title", title: @post.title%>

<p><%=@post.description %></p>
<hr>

<% if logged_in? %>
<div class="well">
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/validation_errors', object: @comment %>
    <div class="control-group">
      <%= f.label :body, "Leave a comment..." %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit("Create Comment", class: 'btn btn-primary') %>

  <% end %>
</div>
<% end %>

<h5>Comments</h5>

<% @post.reload.comments.each do |comment| %>
  <%= render "comments/comment", comment: comment, show_post: false %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.slug %>_votes').html("<%= @post.diff_votes %> votes")
<% else %>
  alert("you can only vote on a post once")
<% end %>