config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    # pertains to individual members of a post
    member do 
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:create, :show, :new]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  before_save :generate_slug

  sluggable_column :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user
  before_action :require_admin, only: [:new, :create]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category has been created."
      redirect_to root_path
    else
      render :new
    end
  end 

  def show
    @category = Category.find_by slug: params[:id]
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>

<%= render 'shared/validation_errors', object: @category %>


<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit "Create Category", class: "btn btn-success" %>
  <% end %>

</div>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>